package dev.pi.cli;

enum PiAppAction {
    INTERRUPT,
    CLEAR,
    EXIT,
    SUSPEND,
    EXTERNAL_EDITOR,
    RESUME,
    CYCLE_MODEL_FORWARD,
    CYCLE_MODEL_BACKWARD,
    CYCLE_THINKING_LEVEL,
    SELECT_MODEL,
    EXPAND_TOOLS,
    TOGGLE_THINKING,
    FOLLOW_UP,
    DEQUEUE,
    PASTE_IMAGE,
    NEW_SESSION,
    TREE,
    FORK,
    TOGGLE_SESSION_NAMED_FILTER
}
