package dev.pi.cli;

enum PiAppAction {
    INTERRUPT,
    RESUME,
    CYCLE_MODEL_FORWARD,
    CYCLE_MODEL_BACKWARD,
    CYCLE_THINKING_LEVEL,
    NEW_SESSION,
    TREE,
    FORK,
    TOGGLE_SESSION_NAMED_FILTER
}
